name: mg
dependencies:
# dev environment
  - python=3.7
  - python-graphviz

# documentation
  - sphinx=3.0.4
  - nbsphinx
  - notebook
  - conda-forge::pydata-sphinx-theme
  - matplotlib
  - pip
  - pip:
    - rst2pdf
    - nest_asyncio

# metagraph dependencies (so setup.py develop doesn't pip install them)
  - importlib_metadata
  - numpy
  - networkx
  - pandas
  - scipy
  - dask
  - conda-forge::donfig
  - conda-forge::websockets
